### ISSUE TITLE
no 'pipe' directory

### ISSUE THREAD

**Issue by dnbuckley** [thinhong/MethPanel#1]
Hello

The instructions say to run MethPanel do
> python "/path/to/MethPanel/pipe/run_Bpipe.py" $sample_config $system_config

I don't see a 'pipe/' directory in the MethPanel directory when I clone the repo, or on the repo page.

Thanks
DB

**Comment by thinhong** [comment]
Dear Buckley,

Thank you for your interest in MethPanel. Due to some unexpected issues, we have to fix the tool for a while therefore we have yet to upload the full directory on github. We expected to finish it next month. We will inform you asap when it is available to use.

Best regards,
TO.

**Comment by thinhong** [comment]
> Hello
> 
> The instructions say to run MethPanel do
> 
> > python "/path/to/MethPanel/pipe/run_Bpipe.py" $sample_config $system_config
> 
> I don't see a 'pipe/' directory in the MethPanel directory when I clone the repo, or on the repo page.
> 
> Thanks
> DB

Dear Buckley,

MethPanel is now fully available. Sorry for the inconvenience that may have been caused to you. Feel free to ask us again if there is any problem.

Best regards,
TO.
